# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dcpp_slope <- function(x, y) {
    .Call(`_dcpp_dcpp_slope`, x, y)
}

dcpp_sum <- function(x) {
    .Call(`_dcpp_dcpp_sum`, x)
}

rcpp_hello_world <- function() {
    .Call(`_dcpp_rcpp_hello_world`)
}

