# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dcpp_fib <- function(n) {
    .Call('_dcpp_dcpp_fib', PACKAGE = 'dcpp', n)
}

dcpp_slope <- function(x, y) {
    .Call('_dcpp_dcpp_slope', PACKAGE = 'dcpp', x, y)
}

dcpp_sum <- function(r_vector) {
    .Call('_dcpp_dcpp_sum', PACKAGE = 'dcpp', r_vector)
}

